<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150301152202 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_link ADD sortkey INT NOT NULL, CHANGE description description LONGTEXT NOT NULL");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_issue ADD sortkey INT NOT NULL");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_solution ADD sortkey INT NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_issue DROP sortkey");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_link DROP sortkey, CHANGE description description VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_solution DROP sortkey");
	}
}