<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150303073716 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_link ADD asset VARCHAR(40) DEFAULT NULL, CHANGE uri uri VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_link ADD CONSTRAINT FK_5BB764B02AF5A5C FOREIGN KEY (asset) REFERENCES typo3_media_domain_model_asset (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_5BB764B02AF5A5C ON typo3_ihs_domain_model_link (asset)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_link DROP FOREIGN KEY FK_5BB764B02AF5A5C");
		$this->addSql("DROP INDEX IDX_5BB764B02AF5A5C ON typo3_ihs_domain_model_link");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_link DROP asset, CHANGE uri uri VARCHAR(255) NOT NULL");
	}
}