<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141029163106 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE typo3_ihs_domain_model_advisory ADD author VARCHAR(255) DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_issue CHANGE description description LONGTEXT DEFAULT NULL, CHANGE reporter reporter VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_solution CHANGE description description LONGTEXT DEFAULT NULL, CHANGE author author VARCHAR(255) DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE typo3_ihs_domain_model_advisory DROP author, CHANGE description description LONGTEXT NOT NULL");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_issue CHANGE description description LONGTEXT NOT NULL, CHANGE reporter reporter VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE typo3_ihs_domain_model_solution CHANGE description description LONGTEXT NOT NULL, CHANGE author author VARCHAR(255) NOT NULL");
	}
}