TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: 'PersistedUsernamePasswordProvider'
            requestPatterns:
              controllerObjectName: 'TYPO3\IHS\Controller\.*'
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package':    'TYPO3.IHS'
                '@controller': 'Login'
                '@action':     'index'
                '@format':     'html'
